FROM resin/%%RESIN_MACHINE_NAME%%-alpine-node:slim

#RUN apt-get update && apt-get install -yq node-gyp && \
#    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY package.json package.json

RUN JOBS=MAX npm install --production --unsafe-perm && rm -rf /tmp/*

COPY . ./

CMD ["npm", "start"]
