FROM resin/%%RESIN_MACHINE_NAME%%-node

RUN apt-get update && apt-get install -yq pip python-dbus virtualenv setuptools python-sense-hat && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY package.json package.json
RUN JOBS=MAX npm install --production
COPY . ./

CMD ["npm", "start"]
