FROM resin/%%RESIN_MACHINE_NAME%%-alpine-node

WORKDIR /usr/src/app

COPY package.json package.json
RUN git clone https://github.com/rupnikj/nodeimu --recursive && \
  cd nodeimu && \
  npm rm nan node-gyp && npm i nan node-gyp && \
  npm install -g && \
  cd .. && rm -rf nodeimu

#  rm -rf RTIMULib2 && \
#  git clone https://github.com/jeff-loughlin/RTIMULib2.git && \

# RUN cd /usr/src/app && npm install --production --unsafe-perm

COPY . ./

CMD ["npm", "start"]
